name: Cross-Platform CMake Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, debian-12, debian-11, fedora-39, fedora-38, archlinux, macos-14, macos-13]
        arch: [x86_64, arm64]
        exclude:
          - os: archlinux
            arch: arm64  # Arch Linux ARM builds require special handling
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: echo "Using architecture: ${{ matrix.arch }}"

    - name: Install dependencies (Debian/Ubuntu)
      if: runner.os == 'Linux' && contains(matrix.os, 'ubuntu') || contains(matrix.os, 'debian')
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential libssl-dev libsecret-1-dev libglib2.0-dev

    - name: Install dependencies (Fedora)
      if: runner.os == 'Linux' && contains(matrix.os, 'fedora')
      run: |
        sudo dnf install -y cmake gcc-c++ make openssl-devel libsecret-devel glib2-devel

    - name: Install dependencies (Arch Linux)
      if: runner.os == 'Linux' && matrix.os == 'archlinux'
      run: |
        sudo pacman -Syu --noconfirm cmake base-devel openssl glib2

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake openssl glib

    - name: Fetch xsimd
      run: |
        git clone https://github.com/xtensor-stack/xsimd.git external/xsimd

    - name: Configure CMake
      run: cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: |
        cd build
        make -j$(nproc || sysctl -n hw.ncpu)

    - name: Test
      working-directory: build
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
